require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0.0
  UseCache: true
  NewCops: enable
  Exclude:
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'vendor/bundle/**/*'
    - 'lib/tasks/*.rake'
    - 'config/**/*'
    - 'spec/*_helper.rb'
    - 'log/*'
    - 'tmp/**/*'

Style/Documentation:
  Enabled: false
Rails/ReflectionClassName:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
