name: Docker Image CI

on: [push, pull_request]

env:
  TEST_TAG: vnesorses/frontend:test
  LATEST_TAG: vnesorses/frontend:latest
  GAR_LOCATION: asia-east1
  GCR_LOCATION: asia-east1
  SERVICE: frontend
  PROJECT_ID: vnesorses
  REPOSITORY: deployment

jobs:
  build-frontend:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./frontend/
        tags: ${{ env.LATEST_TAG }}
        build-args: |
          BACKEND_URL=${{ secrets.BACKEND_URL }}
          STORAGE_URL=${{ secrets.STORAGE_URL }}
          BUCKET_NAME=${{ secrets.BUCKET_NAME }}
          ASSETS_DIR=${{ secrets.ASSETS_DIR }}
    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/385261181840/locations/global/workloadIdentityPools/github-action/providers/github'
        service_account: 'app-service-account@vnesorses.iam.gserviceaccount.com'
    - name: Docker Auth
      id: docker-auth
      uses: 'docker/login-action@v1'
      with:
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'
        registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'
    - name: Build and Push Container
      run: |-
        docker tag ${{ env.LATEST_TAG }} "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
        docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        service: ${{ env.SERVICE }}
        region: ${{ env.GCR_LOCATION }}
        image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}
